#page title
page_title                                : Bumper - Car Advertising                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1448139087                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/us/app/bumper-car-advertising/id1448139087                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/512x512bb.jpg                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Bumper - Car Advertising                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Bumper is a marketplace for our users and brands. Brands can leverage people’s real-life networks.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.

include: [".well-known"]

# Information About Yourself
your_name                                 : Hunter Yost                                
your_link                                 : https://bumperapp.us
your_city                                 : Philadelphia, PA
email_address                             : hunter@bumperapp.us
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Teamwork Makes the Dream Work
    description                           : Bumper allows  brands to leverage a Driver’s style and personality, with creative, sleek, cool ads.  We are all about perfect matches between our drivers and our companies.
    fontawesome_icon_name                 : users
    
  - title                                 : Innovative Ads
    description                           : We not only use smaller, eye-catching ads located at different angles on different areas of a driver’s car (we can make big ads too!), but we use insanely creative marketing techniques.
    fontawesome_icon_name                 : ad

  - title                                 : Effective Ads Means Incentivized Drivers
    description                           : Of course we can track a driver’s miles… so what… doesn’t mean an ad is effective. We think two things are important - Where a car is parked, and who is the driver and what is their network
    fontawesome_icon_name                 : smile-wink

  - title                                 : Pricing
    description                           : This whole thing only works if we are all making some $$ right.  Driver’s want to make some cash monthly, and have the potential for bonuses if they can prove their worth.
    fontawesome_icon_name                 : dollar-sign

  - title                                 : Easy to Tweak
    description                           : Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Feature List
    description                           : Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : star

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#fff"
topbar_transparency                       : 1
topbar_title_color                        : "#262626"

cover_overlay_color                       : "#128cd9"
cover_overlay_transparency                : 0.9

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#efefef"

link_color                                : "#128cd9"

app_title_color                           : "#fafafa"
app_price_color                           : "#fafafa"
app_description_color                     : "#fafafa"

feature_title_color                       : "#262626"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#128cd9"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
