#page title
page_title                                : Bumper - Car Advertising                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1448139087                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/us/app/bumper-car-advertising/id1448139087                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/512x512bb.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Bumper - Car Advertising                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Bumper connects brands with personal brand reps. Brands can leverage people’s real-life networks.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.

include: [".well-known"]

# Information About Yourself
your_name                                 : Hunter Yost                                
your_link                                 : https://bumperapp.us
your_city                                 : Philadelphia, PA
email_address                             : hunter@bumperapp.us
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Teamwork Makes the Dream Work
    description                           : Bumper allows brands to leverage an individual’s style, personality and network.  We strive for perfect matches between our users and our companies.
    fontawesome_icon_name                 : users
    
  - title                                 : Services
    description                           : Brand reps can provide services such as- advertising on their car, distributing print materials or sample products, wearing branded clothing, etc.  Brands have the option to request more unique services as well.
    fontawesome_icon_name                 : smile-wink

  - title                                 : Effective Marketing Means Targeted Marketing
    description                           : Building a brand through a personal brand rep is a proven technique.  We match brands with the right representatives to get products and services to people in your market.
    fontawesome_icon_name                 : ad

  - title                                 : Innovative Marketing
    description                           : It is important to get your product or service to the people who want it.  Personal referral is the strongest way to acquire new customers.  Matching with a brand rep through our app is an effective, new way to get customers.
    fontawesome_icon_name                 : lightbulb

  - title                                 : Data and Metrics
    description                           : We collect data through the use of QR code scans, vehicle location, and photo uploads to let you know which brand reps are extra effective.  
    fontawesome_icon_name                 : chart-bar
  
  - title                                 : Pricing
    description                           : Every person’s network has different strengths and value.  We let brand reps sell themselves and select their own price point for their service.  But we also leave room for brands to make offers and negotiate.
    fontawesome_icon_name                 : dollar-sign

  - title                                 : Privacy and Respect
    description                           : We protect our users' information, we only allow verified brands/companies view full profiles.
    fontawesome_icon_name                 : user-shield



# Theme Settings
topbar_color                              : "#fff"
topbar_transparency                       : 1
topbar_title_color                        : "#262626"

cover_overlay_color                       : "#6C5C96"
cover_overlay_transparency                : 0.9

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#efefef"

link_color                                : "#6C5C96"

app_title_color                           : "#fafafa"
app_price_color                           : "#fafafa"
app_description_color                     : "#fafafa"

feature_title_color                       : "#262626"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#6C5C96"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
