#page title
page_title                                : Bumper - The QR Code Network                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1448139087                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/us/app/bumper-car-advertising/id1448139087                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/512x512bb.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Bumper - The QR Code Network                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Dynamic QR codes for use located around Philadelphia.  Search our database, find the locations you want, and link to any URL.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.

include: [".well-known"]

# Information About Yourself
your_name                                 : Hunter Yost                                
your_link                                 : https://bumperapp.us
your_city                                 : Philadelphia, PA
email_address                             : hunter@bumperapp.us
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Targeted Marketing
    description                           : Use our detailed search feature to find locations in your target market.  Then run different promotional campaigns by linking a website to the QR codes.
    fontawesome_icon_name                 : users
    
  - title                                 : Flexibility
    description                           : Dynamic QR codes allow the URL to be changed so you can link to different websites and make changes as often as you want.  They can also be password protected.  If you want to use a QR code for a specific reason contact us and we’ll be happy to see if it is possible - Hunter@bumperapp.us.
    fontawesome_icon_name                 : smile-wink

  - title                                 : Innovative Marketing
    description                           : Using our branded QR codes is a fun, interactive way to get customers to your digital marketplace, give out discounts, or run other fun promotional campaigns.  Have an idea you want to run through our QR network - Contact us - Hunter@bumperapp.us.
    fontawesome_icon_name                 : ad

  - title                                 : Data and Metrics
    description                           : When people scan we collect the data.  Unique users, conversions time of scan, location, and type of phone.  And we get all of that data to you, either through your own google analytics or our monthly report.
    fontawesome_icon_name                 : lightbulb

  - title                                 : Pricing
    description                           : Every QR code location has different value.  We let our members select their own price point for their QR Codes.  But we also leave room for offers and negotiation.  
    fontawesome_icon_name                 : chart-bar
  
  - title                                 : Privacy and Respect
    description                           : Our network of QR Codes is created by our users.  Use of the QR code network must be approved by both a Bumper administrator and the user who hosts the QR code.
    fontawesome_icon_name                 : dollar-sign


# Theme Settings
topbar_color                              : "#fff"
topbar_transparency                       : 1
topbar_title_color                        : "#262626"

cover_overlay_color                       : "#6C5C96"
cover_overlay_transparency                : 0.9

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#efefef"

link_color                                : "#6C5C96"

app_title_color                           : "#fafafa"
app_price_color                           : "#fafafa"
app_description_color                     : "#fafafa"

feature_title_color                       : "#262626"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#6C5C96"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
